
struct Orders_OD : Encodable, Decodable {
	var store_id : Int?
	var pick_up_in_store : Bool?
	var payment_method_system_name : String?
	var payment_by : String?
	var customer_currency_code : String?
	var currency_rate : Float?
	var customer_tax_display_type_id : Int?
	var vat_number : String?
	var order_subtotal_incl_tax : Float?
	var order_subtotal_excl_tax : Float?
	var order_sub_total_discount_incl_tax : Float?
	var order_sub_total_discount_excl_tax : Float?
	var order_shipping_incl_tax : Float?
	var order_shipping_excl_tax : Float?
	var payment_method_additional_fee_incl_tax : Float?
	var payment_method_additional_fee_excl_tax : Float?
	var tax_rates : String?
	var order_tax : Float?
	var order_discount : Float?
	var order_total : Float?
	var refunded_amount : Float?
	var reward_points_were_added : String?
	var checkout_attribute_description : String?
	var customer_language_id : Int?
	var affiliate_id : Int?
	var customer_ip : String?
	var authorization_transaction_id : String?
	var authorization_transaction_code : String?
	var authorization_transaction_result : String?
	var capture_transaction_id : String?
	var capture_transaction_result : String?
	var subscription_transaction_id : String?
	var paid_date_utc : String?
	var shipping_method : String?
	var shipping_rate_computation_method_system_name : String?
	var custom_values_xml : String?
	var deleted : Bool?
	var created_on_utc : String?
	var customer_id : Int?
	var billing_address : Addresses?
	var billing_address_id : Int?
	var order_items : [Order_items_OD]?
	var order_status : String?
	var payment_status : String?
	var shipping_status : String?
	var customer_tax_display_type : String?
	var id : Int?
}
